### ISSUE TITLE
[Feature] Support IceBerg

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1714]
### Description

Support [IceBerg ](https://iceberg.apache.org/)for all data flow.

### sub-tasks

- [ ] https://github.com/apache/incubator-inlong/issues/1519
- [ ] https://github.com/apache/incubator-inlong/issues/1520
- [ ] https://github.com/apache/incubator-inlong/issues/1521

_No response_

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
