### ISSUE TITLE
[Feature] Support ClickHouse

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#1715]
### sub-tasks

- [x] https://github.com/apache/incubator-inlong/issues/1517
- [x] https://github.com/apache/incubator-inlong/issues/1516
- [x] https://github.com/apache/incubator-inlong/issues/1518

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by feihengye** [comment]
I want to do this feature.

**Comment by gosonzhang** [comment]
@feihengye, first of all, thanks for your attention

This is a root issue, involving multiple modules with multiple 
 subtasks. You need to pay attention to the issues you are interested in and try to communicate with the person in charge of receiving the feature.

Thanks!
