### ISSUE TITLE
[Feature][Manager] Inlong manager support getSortSource interface

### ISSUE THREAD

**Issue by vernedeng** [apache/incubator-inlong#2573]
### Description

*getSortSourceConfig*  is the interface used to initialize  SortSDK including service url, topics and other parameters of caches.

- [x] #2574 Controller of getSortSourceConfig
- [x] #2693 Define tables and beans for getSortSource interface
- [x] #2694 Define services for getSortSource interface
- [x] #2798 Fix SortSourceConfig xml file problem

<img width="505" alt="image" src="https://user-images.githubusercontent.com/45282474/154607723-f224b715-9fe1-472c-b57e-66d86c7d728f.png">

### Use case

Type：HTTP

URL：/api/inlong/manager/openapi/sort/getSortSource
Method：Get

Params：?sortClusterName=xxx&sortTaskId=xxx&md5=xxx&apiVersioin=xxx

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
