### ISSUE TITLE
[Umbrella] release InLong 1.1.0

### ISSUE THREAD

**Issue by dockerzhang** [apache/incubator-inlong#3615]
### Describe the proposal

prepare release InLong 1.1.0

### Task list

sub-tasks:

- [x] #3614
- [x] #3613
- [x] #3607
- [x] #3610
- [x] #3609
- [x] #3612 
- [x] #3608
- [x] #3611
- [x] https://github.com/apache/incubator-inlong-website/issues/372

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
