### ISSUE TITLE
[Improve][Log] Upgrade the property file for all modules from log4j to log4j2

### ISSUE THREAD

**Issue by thexiay** [apache/incubator-inlong#4292]
### Describe the proposal

Update all module log4j properties upgrade to log4j2 properties

### Task list

- [ ] 1. sort log4j properties upgrade
- [ ] 2.manager log4j properties upgrade

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
